// Council areas in England and Wales, keyed by ONS name (as returned by
// postcodes.io), with the council's GOV.UK details. Generated by
// scripts/fetch-councils.mjs on 2026-10-05. Do not edit by hand.

export const COUNCILS = {
  "Adur": {
    "slug": "adur",
    "name": "Adur District Council",
    "url": "https://www.adur-worthing.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Amber Valley": {
    "slug": "amber-valley",
    "name": "Amber Valley Borough Council",
    "url": "http://www.ambervalley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "Arun": {
    "slug": "arun",
    "name": "Arun District Council",
    "url": "http://www.arun.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Ashfield": {
    "slug": "ashfield",
    "name": "Ashfield District Council",
    "url": "https://www.ashfield.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Ashford": {
    "slug": "ashford",
    "name": "Ashford Borough Council",
    "url": "https://www.ashford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Babergh": {
    "slug": "babergh",
    "name": "Babergh District Council",
    "url": "https://www.babergh.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "suffolk",
      "name": "Suffolk County Council",
      "url": "http://www.suffolk.gov.uk/"
    }
  },
  "Barking and Dagenham": {
    "slug": "barking-and-dagenham",
    "name": "London Borough of Barking and Dagenham",
    "url": "https://www.lbbd.gov.uk/",
    "tier": "unitary"
  },
  "Barnet": {
    "slug": "barnet",
    "name": "London Borough of Barnet",
    "url": "https://www.barnet.gov.uk/",
    "tier": "unitary"
  },
  "Barnsley": {
    "slug": "barnsley",
    "name": "Barnsley Metropolitan Borough Council",
    "url": "https://www.barnsley.gov.uk/",
    "tier": "unitary"
  },
  "Basildon": {
    "slug": "basildon",
    "name": "Basildon Borough Council",
    "url": "https://www.basildon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Basingstoke and Deane": {
    "slug": "basingstoke-and-deane",
    "name": "Basingstoke and Deane Borough Council",
    "url": "https://www.basingstoke.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Bassetlaw": {
    "slug": "bassetlaw",
    "name": "Bassetlaw District Council",
    "url": "https://www.bassetlaw.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Bath and North East Somerset": {
    "slug": "bath-and-north-east-somerset",
    "name": "Bath and North East Somerset Council",
    "url": "http://www.bathnes.gov.uk/",
    "tier": "unitary"
  },
  "Bedford": {
    "slug": "bedford",
    "name": "Bedford Borough Council",
    "url": "https://www.bedford.gov.uk/",
    "tier": "unitary"
  },
  "Bexley": {
    "slug": "bexley",
    "name": "London Borough of Bexley",
    "url": "https://www.bexley.gov.uk/",
    "tier": "unitary"
  },
  "Birmingham": {
    "slug": "birmingham",
    "name": "Birmingham City Council",
    "url": "https://www.birmingham.gov.uk/",
    "tier": "unitary"
  },
  "Blaby": {
    "slug": "blaby",
    "name": "Blaby District Council",
    "url": "https://www.blaby.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "Blackburn with Darwen": {
    "slug": "blackburn-with-darwen",
    "name": "Blackburn with Darwen Borough Council",
    "url": "https://www.blackburn.gov.uk/",
    "tier": "unitary"
  },
  "Blackpool": {
    "slug": "blackpool",
    "name": "Blackpool Borough Council",
    "url": "https://www.blackpool.gov.uk/Home.aspx",
    "tier": "unitary"
  },
  "Blaenau Gwent": {
    "slug": "blaenau-gwent",
    "name": "Blaenau Gwent County Borough Council",
    "url": "https://www.blaenau-gwent.gov.uk/",
    "tier": "unitary"
  },
  "Bolsover": {
    "slug": "bolsover",
    "name": "Bolsover District Council",
    "url": "https://www.bolsover.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "Bolton": {
    "slug": "bolton",
    "name": "Bolton Metropolitan Borough Council",
    "url": "http://www.bolton.gov.uk/",
    "tier": "unitary"
  },
  "Boston": {
    "slug": "boston",
    "name": "Boston Borough Council",
    "url": "https://www.boston.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "Bournemouth, Christchurch and Poole": {
    "slug": "bournemouth-christchurch-poole",
    "name": "Bournemouth, Christchurch and Poole Council",
    "url": "https://www.bcpcouncil.gov.uk/",
    "tier": "unitary"
  },
  "Bracknell Forest": {
    "slug": "bracknell-forest",
    "name": "Bracknell Forest Council",
    "url": "https://www.bracknell-forest.gov.uk/",
    "tier": "unitary"
  },
  "Bradford": {
    "slug": "bradford",
    "name": "City of Bradford Metropolitan District Council",
    "url": "https://www.bradford.gov.uk/",
    "tier": "unitary"
  },
  "Braintree": {
    "slug": "braintree",
    "name": "Braintree District Council",
    "url": "http://www.braintree.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Breckland": {
    "slug": "breckland",
    "name": "Breckland Council",
    "url": "http://www.breckland.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "Brent": {
    "slug": "brent",
    "name": "London Borough of Brent",
    "url": "https://www.brent.gov.uk/",
    "tier": "unitary"
  },
  "Brentwood": {
    "slug": "brentwood",
    "name": "Brentwood Borough Council",
    "url": "http://www.brentwood.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Bridgend": {
    "slug": "bridgend",
    "name": "Bridgend County Borough Council",
    "url": "https://www.bridgend.gov.uk/",
    "tier": "unitary"
  },
  "Brighton and Hove": {
    "slug": "brighton-and-hove",
    "name": "Brighton and Hove City Council",
    "url": "https://www.brighton-hove.gov.uk/",
    "tier": "unitary"
  },
  "Bristol, City of": {
    "slug": "bristol",
    "name": "Bristol City Council",
    "url": "https://www.bristol.gov.uk/",
    "tier": "unitary"
  },
  "Broadland": {
    "slug": "broadland",
    "name": "Broadland District Council",
    "url": "https://www.southnorfolkandbroadland.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "Bromley": {
    "slug": "bromley",
    "name": "London Borough of Bromley",
    "url": "https://www.bromley.gov.uk/",
    "tier": "unitary"
  },
  "Bromsgrove": {
    "slug": "bromsgrove",
    "name": "Bromsgrove District Council",
    "url": "http://www.bromsgrove.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "worcestershire",
      "name": "Worcestershire County Council",
      "url": "http://www.worcestershire.gov.uk"
    }
  },
  "Broxbourne": {
    "slug": "broxbourne",
    "name": "Borough of Broxbourne",
    "url": "https://www.broxbourne.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "Broxtowe": {
    "slug": "broxtowe",
    "name": "Broxtowe Borough Council",
    "url": "https://www.broxtowe.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Buckinghamshire": {
    "slug": "buckinghamshire",
    "name": "Buckinghamshire Council",
    "url": "https://www.buckinghamshire.gov.uk/",
    "tier": "unitary"
  },
  "Burnley": {
    "slug": "burnley",
    "name": "Burnley Borough Council",
    "url": "https://burnley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Bury": {
    "slug": "bury",
    "name": "Bury Metropolitan Borough Council",
    "url": "https://www.bury.gov.uk/",
    "tier": "unitary"
  },
  "Caerphilly": {
    "slug": "caerphilly",
    "name": "Caerphilly County Borough Council",
    "url": "http://www.caerphilly.gov.uk",
    "tier": "unitary"
  },
  "Calderdale": {
    "slug": "calderdale",
    "name": "Calderdale Metropolitan Borough Council",
    "url": "https://www.calderdale.gov.uk/",
    "tier": "unitary"
  },
  "Cambridge": {
    "slug": "cambridge",
    "name": "Cambridge City Council",
    "url": "https://www.cambridge.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "cambridgeshire",
      "name": "Cambridgeshire County Council",
      "url": "https://www.cambridgeshire.gov.uk/"
    }
  },
  "Camden": {
    "slug": "camden",
    "name": "London Borough of Camden",
    "url": "https://www.camden.gov.uk/",
    "tier": "unitary"
  },
  "Cannock Chase": {
    "slug": "cannock-chase",
    "name": "Cannock Chase District Council",
    "url": "http://www.cannockchasedc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "Canterbury": {
    "slug": "canterbury",
    "name": "Canterbury City Council",
    "url": "https://www.canterbury.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Cardiff": {
    "slug": "cardiff",
    "name": "City of Cardiff Council",
    "url": "https://www.cardiff.gov.uk/",
    "tier": "unitary"
  },
  "Carmarthenshire": {
    "slug": "carmarthenshire",
    "name": "Carmarthenshire County Council",
    "url": "https://www.carmarthenshire.gov.wales/home/council-services/",
    "tier": "unitary"
  },
  "Castle Point": {
    "slug": "castle-point",
    "name": "Castle Point Borough Council",
    "url": "https://www.castlepoint.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Central Bedfordshire": {
    "slug": "central-bedfordshire",
    "name": "Central Bedfordshire Council",
    "url": "http://www.centralbedfordshire.gov.uk",
    "tier": "unitary"
  },
  "Ceredigion": {
    "slug": "ceredigion",
    "name": "Ceredigion County Council",
    "url": "https://www.ceredigion.gov.uk/",
    "tier": "unitary"
  },
  "Charnwood": {
    "slug": "charnwood",
    "name": "Charnwood Borough Council",
    "url": "http://www.charnwood.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "Chelmsford": {
    "slug": "chelmsford",
    "name": "Chelmsford City Council",
    "url": "https://www.chelmsford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Cheltenham": {
    "slug": "cheltenham",
    "name": "Cheltenham Borough Council",
    "url": "https://www.cheltenham.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "gloucestershire",
      "name": "Gloucestershire County Council",
      "url": "https://www.gloucestershire.gov.uk/"
    }
  },
  "Cherwell": {
    "slug": "cherwell",
    "name": "Cherwell District Council",
    "url": "https://www.cherwell.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "oxfordshire",
      "name": "Oxfordshire County Council",
      "url": "https://www.oxfordshire.gov.uk/"
    }
  },
  "Cheshire East": {
    "slug": "cheshire-east",
    "name": "Cheshire East Council",
    "url": "https://www.cheshireeast.gov.uk/",
    "tier": "unitary"
  },
  "Cheshire West and Chester": {
    "slug": "cheshire-west-and-chester",
    "name": "Cheshire West and Chester Council",
    "url": "https://www.cheshirewestandchester.gov.uk/",
    "tier": "unitary"
  },
  "Chesterfield": {
    "slug": "chesterfield",
    "name": "Chesterfield Borough Council",
    "url": "https://www.chesterfield.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "Chichester": {
    "slug": "chichester",
    "name": "Chichester District Council",
    "url": "http://www.chichester.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Chorley": {
    "slug": "chorley",
    "name": "Chorley Council",
    "url": "https://chorley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "City of London": {
    "slug": "city-of-london",
    "name": "City of London Corporation",
    "url": "https://www.cityoflondon.gov.uk/",
    "tier": "unitary"
  },
  "Colchester": {
    "slug": "colchester",
    "name": "Colchester City Council",
    "url": "http://www.colchester.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Conwy": {
    "slug": "conwy",
    "name": "Conwy County Borough Council",
    "url": "https://www.conwy.gov.uk",
    "tier": "unitary"
  },
  "Cornwall": {
    "slug": "cornwall",
    "name": "Cornwall Council",
    "url": "https://www.cornwall.gov.uk/",
    "tier": "unitary"
  },
  "Cotswold": {
    "slug": "cotswold",
    "name": "Cotswold District Council",
    "url": "https://www.cotswold.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "gloucestershire",
      "name": "Gloucestershire County Council",
      "url": "https://www.gloucestershire.gov.uk/"
    }
  },
  "County Durham": {
    "slug": "county-durham",
    "name": "Durham County Council",
    "url": "http://www.durham.gov.uk/",
    "tier": "unitary"
  },
  "Coventry": {
    "slug": "coventry",
    "name": "Coventry City Council",
    "url": "https://www.coventry.gov.uk/",
    "tier": "unitary"
  },
  "Crawley": {
    "slug": "crawley",
    "name": "Crawley Borough Council",
    "url": "https://crawley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Croydon": {
    "slug": "croydon",
    "name": "London Borough of Croydon",
    "url": "http://www.croydon.gov.uk",
    "tier": "unitary"
  },
  "Cumberland": {
    "slug": "cumberland",
    "name": "Cumberland Council",
    "url": "https://www.cumberland.gov.uk/",
    "tier": "unitary"
  },
  "Dacorum": {
    "slug": "dacorum",
    "name": "Dacorum Borough Council",
    "url": "http://www.dacorum.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "Darlington": {
    "slug": "darlington",
    "name": "Darlington Borough Council",
    "url": "https://www.darlington.gov.uk/",
    "tier": "unitary"
  },
  "Dartford": {
    "slug": "dartford",
    "name": "Dartford Borough Council",
    "url": "http://www.dartford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Denbighshire": {
    "slug": "denbighshire",
    "name": "Denbighshire County Council",
    "url": "https://www.denbighshire.gov.uk/",
    "tier": "unitary"
  },
  "Derby": {
    "slug": "derby",
    "name": "Derby City",
    "url": "https://www.derby.gov.uk/",
    "tier": "unitary"
  },
  "Derbyshire Dales": {
    "slug": "derbyshire-dales",
    "name": "Derbyshire Dales District Council",
    "url": "https://www.derbyshiredales.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "Doncaster": {
    "slug": "doncaster",
    "name": "Doncaster Metropolitan Borough Council",
    "url": "http://www.doncaster.gov.uk/",
    "tier": "unitary"
  },
  "Dorset": {
    "slug": "dorset",
    "name": "Dorset Council",
    "url": "https://www.dorsetcouncil.gov.uk/",
    "tier": "unitary"
  },
  "Dover": {
    "slug": "dover",
    "name": "Dover District Council",
    "url": "https://www.dover.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Dudley": {
    "slug": "dudley",
    "name": "Dudley Metropolitan Borough Council",
    "url": "https://www.dudley.gov.uk/",
    "tier": "unitary"
  },
  "Ealing": {
    "slug": "ealing",
    "name": "London Borough of Ealing",
    "url": "https://www.ealing.gov.uk/",
    "tier": "unitary"
  },
  "East Cambridgeshire": {
    "slug": "east-cambridgeshire",
    "name": "East Cambridgeshire District Council",
    "url": "http://www.eastcambs.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "cambridgeshire",
      "name": "Cambridgeshire County Council",
      "url": "https://www.cambridgeshire.gov.uk/"
    }
  },
  "East Devon": {
    "slug": "east-devon",
    "name": "East Devon District Council",
    "url": "http://eastdevon.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "East Hampshire": {
    "slug": "east-hampshire",
    "name": "East Hampshire District Council",
    "url": "http://www.easthants.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "East Hertfordshire": {
    "slug": "east-hertfordshire",
    "name": "East Hertfordshire District Council",
    "url": "https://www.eastherts.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "East Lindsey": {
    "slug": "east-lindsey",
    "name": "East Lindsey District Council",
    "url": "https://www.e-lindsey.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "East Riding of Yorkshire": {
    "slug": "east-riding-of-yorkshire",
    "name": "East Riding of Yorkshire Council",
    "url": "http://www.eastriding.gov.uk/",
    "tier": "unitary"
  },
  "East Staffordshire": {
    "slug": "east-staffordshire",
    "name": "East Staffordshire Borough Council",
    "url": "https://www.eaststaffsbc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "East Suffolk": {
    "slug": "east-suffolk",
    "name": "East Suffolk District Council",
    "url": "https://www.eastsuffolk.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "suffolk",
      "name": "Suffolk County Council",
      "url": "http://www.suffolk.gov.uk/"
    }
  },
  "Eastbourne": {
    "slug": "eastbourne",
    "name": "Eastbourne Borough Council",
    "url": "https://www.lewes-eastbourne.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "east-sussex",
      "name": "East Sussex County Council",
      "url": "https://www.eastsussex.gov.uk/"
    }
  },
  "Eastleigh": {
    "slug": "eastleigh",
    "name": "Eastleigh Borough Council",
    "url": "http://www.eastleigh.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Elmbridge": {
    "slug": "elmbridge",
    "name": "Elmbridge Borough Council",
    "url": "http://www.elmbridge.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Enfield": {
    "slug": "enfield",
    "name": "London Borough of Enfield",
    "url": "https://new.enfield.gov.uk/",
    "tier": "unitary"
  },
  "Epping Forest": {
    "slug": "epping-forest",
    "name": "Epping Forest District Council",
    "url": "https://www.eppingforestdc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Epsom and Ewell": {
    "slug": "epsom-and-ewell",
    "name": "Epsom and Ewell Borough Council",
    "url": "http://www.epsom-ewell.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Erewash": {
    "slug": "erewash",
    "name": "Erewash Borough Council",
    "url": "https://www.erewash.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "Exeter": {
    "slug": "exeter",
    "name": "Exeter City Council",
    "url": "https://exeter.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "Fareham": {
    "slug": "fareham",
    "name": "Fareham Borough Council",
    "url": "https://www.fareham.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Fenland": {
    "slug": "fenland",
    "name": "Fenland District Council",
    "url": "http://www.fenland.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "cambridgeshire",
      "name": "Cambridgeshire County Council",
      "url": "https://www.cambridgeshire.gov.uk/"
    }
  },
  "Flintshire": {
    "slug": "flintshire",
    "name": "Flintshire County Council",
    "url": "http://www.flintshire.gov.uk",
    "tier": "unitary"
  },
  "Folkestone and Hythe": {
    "slug": "folkestone-hythe",
    "name": "Folkestone and Hythe District Council",
    "url": "https://www.folkestone-hythe.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Forest of Dean": {
    "slug": "forest-of-dean",
    "name": "Forest of Dean District Council",
    "url": "https://www.fdean.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "gloucestershire",
      "name": "Gloucestershire County Council",
      "url": "https://www.gloucestershire.gov.uk/"
    }
  },
  "Fylde": {
    "slug": "fylde",
    "name": "Fylde Borough Council",
    "url": "https://www.fylde.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Gateshead": {
    "slug": "gateshead",
    "name": "Gateshead Metropolitan Borough Council",
    "url": "https://www.gateshead.gov.uk/",
    "tier": "unitary"
  },
  "Gedling": {
    "slug": "gedling",
    "name": "Gedling Borough Council",
    "url": "https://www.gedling.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Gloucester": {
    "slug": "gloucester",
    "name": "Gloucester City Council",
    "url": "http://www.gloucester.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "gloucestershire",
      "name": "Gloucestershire County Council",
      "url": "https://www.gloucestershire.gov.uk/"
    }
  },
  "Gosport": {
    "slug": "gosport",
    "name": "Gosport Borough Council",
    "url": "https://www.gosport.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Gravesham": {
    "slug": "gravesham",
    "name": "Gravesham Borough Council",
    "url": "http://www.gravesham.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Great Yarmouth": {
    "slug": "great-yarmouth",
    "name": "Great Yarmouth Borough Council",
    "url": "https://www.great-yarmouth.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "Greenwich": {
    "slug": "greenwich",
    "name": "Royal Borough of Greenwich",
    "url": "http://www.royalgreenwich.gov.uk/",
    "tier": "unitary"
  },
  "Guildford": {
    "slug": "guildford",
    "name": "Guildford Borough Council",
    "url": "https://www.guildford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Gwynedd": {
    "slug": "gwynedd",
    "name": "Gwynedd Council",
    "url": "https://www.gwynedd.llyw.cymru/",
    "tier": "unitary"
  },
  "Hackney": {
    "slug": "hackney",
    "name": "London Borough of Hackney",
    "url": "https://hackney.gov.uk/",
    "tier": "unitary"
  },
  "Halton": {
    "slug": "halton",
    "name": "Halton Borough Council",
    "url": "https://www3.halton.gov.uk/",
    "tier": "unitary"
  },
  "Hammersmith and Fulham": {
    "slug": "hammersmith-and-fulham",
    "name": "London Borough of Hammersmith & Fulham",
    "url": "http://www.lbhf.gov.uk/",
    "tier": "unitary"
  },
  "Harborough": {
    "slug": "harborough",
    "name": "Harborough District Council",
    "url": "http://www.harborough.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "Haringey": {
    "slug": "haringey",
    "name": "London Borough of Haringey",
    "url": "https://www.haringey.gov.uk/",
    "tier": "unitary"
  },
  "Harlow": {
    "slug": "harlow",
    "name": "Harlow Council",
    "url": "http://www.harlow.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Harrow": {
    "slug": "harrow",
    "name": "London Borough of Harrow",
    "url": "https://www.harrow.gov.uk/",
    "tier": "unitary"
  },
  "Hart": {
    "slug": "hart",
    "name": "Hart District Council",
    "url": "https://www.hart.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Hartlepool": {
    "slug": "hartlepool",
    "name": "Hartlepool Borough Council",
    "url": "http://www.hartlepool.gov.uk",
    "tier": "unitary"
  },
  "Hastings": {
    "slug": "hastings",
    "name": "Hastings Borough Council",
    "url": "https://www.hastings.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "east-sussex",
      "name": "East Sussex County Council",
      "url": "https://www.eastsussex.gov.uk/"
    }
  },
  "Havant": {
    "slug": "havant",
    "name": "Havant Borough Council",
    "url": "http://www.havant.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Havering": {
    "slug": "havering",
    "name": "London Borough of Havering",
    "url": "https://www.havering.gov.uk/",
    "tier": "unitary"
  },
  "Herefordshire, County of": {
    "slug": "herefordshire",
    "name": "Herefordshire Council",
    "url": "https://www.herefordshire.gov.uk/",
    "tier": "unitary"
  },
  "Hertsmere": {
    "slug": "hertsmere",
    "name": "Hertsmere Borough Council",
    "url": "https://www.hertsmere.gov.uk/home.aspx",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "High Peak": {
    "slug": "high-peak",
    "name": "High Peak Borough Council",
    "url": "https://www.highpeak.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "Hillingdon": {
    "slug": "hillingdon",
    "name": "London Borough of Hillingdon",
    "url": "https://www.hillingdon.gov.uk/",
    "tier": "unitary"
  },
  "Hinckley and Bosworth": {
    "slug": "hinckley-and-bosworth",
    "name": "Hinckley and Bosworth Borough Council",
    "url": "https://www.hinckley-bosworth.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "Horsham": {
    "slug": "horsham",
    "name": "Horsham District Council",
    "url": "https://www.horsham.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Hounslow": {
    "slug": "hounslow",
    "name": "London Borough of Hounslow",
    "url": "https://www.hounslow.gov.uk/",
    "tier": "unitary"
  },
  "Huntingdonshire": {
    "slug": "huntingdonshire",
    "name": "Huntingdonshire District Council",
    "url": "https://www.huntingdonshire.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "cambridgeshire",
      "name": "Cambridgeshire County Council",
      "url": "https://www.cambridgeshire.gov.uk/"
    }
  },
  "Hyndburn": {
    "slug": "hyndburn",
    "name": "Hyndburn Borough Council",
    "url": "https://www.hyndburnbc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Ipswich": {
    "slug": "ipswich",
    "name": "Ipswich Borough Council",
    "url": "https://www.ipswich.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "suffolk",
      "name": "Suffolk County Council",
      "url": "http://www.suffolk.gov.uk/"
    }
  },
  "Isle of Anglesey": {
    "slug": "isle-of-anglesey",
    "name": "Isle of Anglesey County Council",
    "url": "https://www.anglesey.gov.uk",
    "tier": "unitary"
  },
  "Isle of Wight": {
    "slug": "isle-of-wight",
    "name": "Isle of Wight Council",
    "url": "https://www.iow.gov.uk/",
    "tier": "unitary"
  },
  "Isles of Scilly": {
    "slug": "isles-of-scilly",
    "name": "Council of the Isles of Scilly",
    "url": "http://www.scilly.gov.uk",
    "tier": "unitary"
  },
  "Islington": {
    "slug": "islington",
    "name": "London Borough of Islington",
    "url": "https://www.islington.gov.uk/",
    "tier": "unitary"
  },
  "Kensington and Chelsea": {
    "slug": "kensington-and-chelsea",
    "name": "Royal Borough of Kensington and Chelsea",
    "url": "https://www.rbkc.gov.uk/",
    "tier": "unitary"
  },
  "King's Lynn and West Norfolk": {
    "slug": "kings-lynn-and-west-norfolk",
    "name": "Borough Council of Kings Lynn and West Norfolk",
    "url": "http://www.west-norfolk.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "Kingston upon Hull, City of": {
    "slug": "kingston-upon-hull",
    "name": "Hull City Council",
    "url": "https://www.hull.gov.uk",
    "tier": "unitary"
  },
  "Kingston upon Thames": {
    "slug": "kingston-upon-thames",
    "name": "Royal Borough of Kingston upon Thames",
    "url": "https://www.kingston.gov.uk/",
    "tier": "unitary"
  },
  "Kirklees": {
    "slug": "kirklees",
    "name": "Kirklees Council",
    "url": "https://www.kirklees.gov.uk/",
    "tier": "unitary"
  },
  "Knowsley": {
    "slug": "knowsley",
    "name": "Knowsley Metropolitan Borough Council",
    "url": "https://www.knowsley.gov.uk/",
    "tier": "unitary"
  },
  "Lambeth": {
    "slug": "lambeth",
    "name": "London Borough of Lambeth",
    "url": "http://www.lambeth.gov.uk/",
    "tier": "unitary"
  },
  "Lancaster": {
    "slug": "lancaster",
    "name": "Lancaster City Council",
    "url": "https://www.lancaster.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Leeds": {
    "slug": "leeds",
    "name": "Leeds City Council",
    "url": "https://www.leeds.gov.uk/",
    "tier": "unitary"
  },
  "Leicester": {
    "slug": "leicester",
    "name": "Leicester City Council",
    "url": "https://www.leicester.gov.uk/",
    "tier": "unitary"
  },
  "Lewes": {
    "slug": "lewes",
    "name": "Lewes District Council",
    "url": "https://www.lewes-eastbourne.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "east-sussex",
      "name": "East Sussex County Council",
      "url": "https://www.eastsussex.gov.uk/"
    }
  },
  "Lewisham": {
    "slug": "lewisham",
    "name": "London Borough of Lewisham",
    "url": "https://lewisham.gov.uk/",
    "tier": "unitary"
  },
  "Lichfield": {
    "slug": "lichfield",
    "name": "Lichfield District Council",
    "url": "https://www.lichfielddc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "Lincoln": {
    "slug": "lincoln",
    "name": "City of Lincoln Council",
    "url": "http://www.lincoln.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "Liverpool": {
    "slug": "liverpool",
    "name": "Liverpool City Council",
    "url": "https://liverpool.gov.uk/",
    "tier": "unitary"
  },
  "Luton": {
    "slug": "luton",
    "name": "Luton Borough Council",
    "url": "https://m.luton.gov.uk/Page/Show",
    "tier": "unitary"
  },
  "Maidstone": {
    "slug": "maidstone",
    "name": "Maidstone Borough Council",
    "url": "https://maidstone.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Maldon": {
    "slug": "maldon",
    "name": "Maldon District Council",
    "url": "https://www.maldon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Malvern Hills": {
    "slug": "malvern-hills",
    "name": "Malvern Hills District Council",
    "url": "https://www.malvernhills.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "worcestershire",
      "name": "Worcestershire County Council",
      "url": "http://www.worcestershire.gov.uk"
    }
  },
  "Manchester": {
    "slug": "manchester",
    "name": "Manchester City Council",
    "url": "http://www.manchester.gov.uk/",
    "tier": "unitary"
  },
  "Mansfield": {
    "slug": "mansfield",
    "name": "Mansfield District Council",
    "url": "https://www.mansfield.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Medway": {
    "slug": "medway",
    "name": "Medway Council",
    "url": "https://www.medway.gov.uk/",
    "tier": "unitary"
  },
  "Melton": {
    "slug": "melton",
    "name": "Melton Borough Council",
    "url": "http://www.melton.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "Merthyr Tydfil": {
    "slug": "merthyr-tydfil",
    "name": "Merthyr Tydfil County Borough Council",
    "url": "https://www.merthyr.gov.uk",
    "tier": "unitary"
  },
  "Merton": {
    "slug": "merton",
    "name": "London Borough of Merton",
    "url": "http://www.merton.gov.uk/",
    "tier": "unitary"
  },
  "Mid Devon": {
    "slug": "mid-devon",
    "name": "Mid Devon District Council",
    "url": "https://www.middevon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "Mid Suffolk": {
    "slug": "mid-suffolk",
    "name": "Mid Suffolk District Council",
    "url": "https://www.midsuffolk.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "suffolk",
      "name": "Suffolk County Council",
      "url": "http://www.suffolk.gov.uk/"
    }
  },
  "Mid Sussex": {
    "slug": "mid-sussex",
    "name": "Mid Sussex District Council",
    "url": "http://www.midsussex.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Middlesbrough": {
    "slug": "middlesbrough",
    "name": "Middlesbrough Borough Council",
    "url": "https://www.middlesbrough.gov.uk/",
    "tier": "unitary"
  },
  "Milton Keynes": {
    "slug": "milton-keynes",
    "name": "Milton Keynes City Council",
    "url": "https://www.milton-keynes.gov.uk/",
    "tier": "unitary"
  },
  "Mole Valley": {
    "slug": "mole-valley",
    "name": "Mole Valley District Council",
    "url": "https://www.molevalley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Monmouthshire": {
    "slug": "monmouthshire",
    "name": "Monmouthshire County Council",
    "url": "https://www.monmouthshire.gov.uk/",
    "tier": "unitary"
  },
  "Neath Port Talbot": {
    "slug": "neath-port-talbot",
    "name": "Neath Port Talbot County Borough Council",
    "url": "http://www.neath-porttalbot.gov.uk",
    "tier": "unitary"
  },
  "New Forest": {
    "slug": "new-forest",
    "name": "New Forest District Council",
    "url": "https://www.newforest.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Newark and Sherwood": {
    "slug": "newark-and-sherwood",
    "name": "Newark and Sherwood District Council",
    "url": "https://www.newark-sherwooddc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Newcastle upon Tyne": {
    "slug": "newcastle-upon-tyne",
    "name": "Newcastle City Council",
    "url": "https://www.newcastle.gov.uk/",
    "tier": "unitary"
  },
  "Newcastle-under-Lyme": {
    "slug": "newcastle-under-lyme",
    "name": "Newcastle-under-Lyme District Council",
    "url": "https://www.newcastle-staffs.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "Newham": {
    "slug": "newham",
    "name": "London Borough of Newham",
    "url": "https://www.newham.gov.uk/",
    "tier": "unitary"
  },
  "Newport": {
    "slug": "newport",
    "name": "Newport City Council",
    "url": "https://www.newport.gov.uk/",
    "tier": "unitary"
  },
  "North Devon": {
    "slug": "north-devon",
    "name": "North Devon Council",
    "url": "http://www.northdevon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "North East Derbyshire": {
    "slug": "north-east-derbyshire",
    "name": "North East Derbyshire District Council",
    "url": "https://www.ne-derbyshire.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "North East Lincolnshire": {
    "slug": "north-east-lincolnshire",
    "name": "North East Lincolnshire Council",
    "url": "http://www.nelincs.gov.uk/",
    "tier": "unitary"
  },
  "North Hertfordshire": {
    "slug": "north-hertfordshire",
    "name": "North Hertfordshire District Council",
    "url": "http://www.north-herts.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "North Kesteven": {
    "slug": "north-kesteven",
    "name": "North Kesteven District Council",
    "url": "https://www.n-kesteven.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "North Lincolnshire": {
    "slug": "north-lincolnshire",
    "name": "North Lincolnshire Council",
    "url": "https://www.northlincs.gov.uk/",
    "tier": "unitary"
  },
  "North Norfolk": {
    "slug": "north-norfolk",
    "name": "North Norfolk District Council",
    "url": "https://www.north-norfolk.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "North Northamptonshire": {
    "slug": "north-northamptonshire",
    "name": "North Northamptonshire Council",
    "url": "https://www.northnorthants.gov.uk/",
    "tier": "unitary"
  },
  "North Somerset": {
    "slug": "north-somerset",
    "name": "North Somerset Council",
    "url": "https://www.n-somerset.gov.uk/",
    "tier": "unitary"
  },
  "North Tyneside": {
    "slug": "north-tyneside",
    "name": "North Tyneside Council",
    "url": "https://my.northtyneside.gov.uk/",
    "tier": "unitary"
  },
  "North Warwickshire": {
    "slug": "north-warwickshire",
    "name": "North Warwickshire Borough Council",
    "url": "https://northwarks.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "warwickshire",
      "name": "Warwickshire County Council",
      "url": "https://www.warwickshire.gov.uk/"
    }
  },
  "North West Leicestershire": {
    "slug": "north-west-leicestershire",
    "name": "North West Leicestershire District Council",
    "url": "http://www.nwleics.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "North Yorkshire": {
    "slug": "north-yorkshire",
    "name": "North Yorkshire Council",
    "url": "http://www.northyorks.gov.uk/",
    "tier": "unitary"
  },
  "Northumberland": {
    "slug": "northumberland",
    "name": "Northumberland County Council",
    "url": "https://www.northumberland.gov.uk/",
    "tier": "unitary"
  },
  "Norwich": {
    "slug": "norwich",
    "name": "Norwich City Council",
    "url": "https://www.norwich.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "Nottingham": {
    "slug": "nottingham",
    "name": "Nottingham City Council",
    "url": "https://www.nottinghamcity.gov.uk/",
    "tier": "unitary"
  },
  "Nuneaton and Bedworth": {
    "slug": "nuneaton-and-bedworth",
    "name": "Nuneaton and Bedworth Borough Council",
    "url": "https://www.nuneatonandbedworth.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "warwickshire",
      "name": "Warwickshire County Council",
      "url": "https://www.warwickshire.gov.uk/"
    }
  },
  "Oadby and Wigston": {
    "slug": "oadby-and-wigston",
    "name": "Oadby and Wigston Borough Council",
    "url": "https://www.oadby-wigston.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "leicestershire",
      "name": "Leicestershire County Council",
      "url": "https://www.leicestershire.gov.uk/"
    }
  },
  "Oldham": {
    "slug": "oldham",
    "name": "Oldham Metropolitan Borough Council",
    "url": "https://www.oldham.gov.uk/",
    "tier": "unitary"
  },
  "Oxford": {
    "slug": "oxford",
    "name": "Oxford City Council",
    "url": "https://www.oxford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "oxfordshire",
      "name": "Oxfordshire County Council",
      "url": "https://www.oxfordshire.gov.uk/"
    }
  },
  "Pembrokeshire": {
    "slug": "pembrokeshire",
    "name": "Pembrokeshire County Council",
    "url": "https://www.pembrokeshire.gov.uk",
    "tier": "unitary"
  },
  "Pendle": {
    "slug": "pendle",
    "name": "Pendle Borough Council",
    "url": "https://www.pendle.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Peterborough": {
    "slug": "peterborough",
    "name": "Peterborough City Council",
    "url": "http://www.peterborough.gov.uk/",
    "tier": "unitary"
  },
  "Plymouth": {
    "slug": "plymouth",
    "name": "Plymouth City Council",
    "url": "https://www.plymouth.gov.uk/",
    "tier": "unitary"
  },
  "Portsmouth": {
    "slug": "portsmouth",
    "name": "Portsmouth City Council",
    "url": "https://www.portsmouth.gov.uk/",
    "tier": "unitary"
  },
  "Powys": {
    "slug": "powys",
    "name": "Powys County Council",
    "url": "http://www.powys.gov.uk",
    "tier": "unitary"
  },
  "Preston": {
    "slug": "preston",
    "name": "Preston City Council",
    "url": "https://www.preston.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Reading": {
    "slug": "reading",
    "name": "Reading Borough Council",
    "url": "https://www.reading.gov.uk/",
    "tier": "unitary"
  },
  "Redbridge": {
    "slug": "redbridge",
    "name": "London Borough of Redbridge",
    "url": "https://www.redbridge.gov.uk/",
    "tier": "unitary"
  },
  "Redcar and Cleveland": {
    "slug": "redcar-and-cleveland",
    "name": "Redcar and Cleveland Borough Council",
    "url": "https://www.redcar-cleveland.gov.uk/",
    "tier": "unitary"
  },
  "Redditch": {
    "slug": "redditch",
    "name": "Redditch Borough Council",
    "url": "https://www.redditchbc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "worcestershire",
      "name": "Worcestershire County Council",
      "url": "http://www.worcestershire.gov.uk"
    }
  },
  "Reigate and Banstead": {
    "slug": "reigate-and-banstead",
    "name": "Reigate and Banstead Borough Council",
    "url": "https://www.reigate-banstead.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Rhondda Cynon Taf": {
    "slug": "rhondda-cynon-taff",
    "name": "Rhondda Cynon Taf County Borough Council",
    "url": "https://www.rctcbc.gov.uk/",
    "tier": "unitary"
  },
  "Ribble Valley": {
    "slug": "ribble-valley",
    "name": "Ribble Valley Borough Council",
    "url": "https://www.ribblevalley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Richmond upon Thames": {
    "slug": "richmond-upon-thames",
    "name": "London Borough of Richmond upon Thames",
    "url": "http://www.richmond.gov.uk/",
    "tier": "unitary"
  },
  "Rochdale": {
    "slug": "rochdale",
    "name": "Rochdale Metropolitan Borough Council",
    "url": "http://www.rochdale.gov.uk/",
    "tier": "unitary"
  },
  "Rochford": {
    "slug": "rochford",
    "name": "Rochford District Council",
    "url": "https://www.rochford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Rossendale": {
    "slug": "rossendale",
    "name": "Rossendale Borough Council",
    "url": "https://www.rossendale.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Rother": {
    "slug": "rother",
    "name": "Rother District Council",
    "url": "http://www.rother.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "east-sussex",
      "name": "East Sussex County Council",
      "url": "https://www.eastsussex.gov.uk/"
    }
  },
  "Rotherham": {
    "slug": "rotherham",
    "name": "Rotherham Metropolitan Borough Council",
    "url": "https://www.rotherham.gov.uk/",
    "tier": "unitary"
  },
  "Rugby": {
    "slug": "rugby",
    "name": "Rugby Borough Council",
    "url": "http://www.rugby.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "warwickshire",
      "name": "Warwickshire County Council",
      "url": "https://www.warwickshire.gov.uk/"
    }
  },
  "Runnymede": {
    "slug": "runnymede",
    "name": "Runnymede Borough Council",
    "url": "https://www.runnymede.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Rushcliffe": {
    "slug": "rushcliffe",
    "name": "Rushcliffe Borough Council",
    "url": "https://www.rushcliffe.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "nottinghamshire",
      "name": "Nottinghamshire County Council",
      "url": "http://www.nottinghamshire.gov.uk/"
    }
  },
  "Rushmoor": {
    "slug": "rushmoor",
    "name": "Rushmoor Borough Council",
    "url": "http://www.rushmoor.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Rutland": {
    "slug": "rutland",
    "name": "Rutland County Council",
    "url": "https://www.rutland.gov.uk/",
    "tier": "unitary"
  },
  "Salford": {
    "slug": "salford",
    "name": "Salford City Council",
    "url": "https://www.salford.gov.uk/",
    "tier": "unitary"
  },
  "Sandwell": {
    "slug": "sandwell",
    "name": "Sandwell Metropolitan Borough Council",
    "url": "http://www.sandwell.gov.uk/",
    "tier": "unitary"
  },
  "Sefton": {
    "slug": "sefton",
    "name": "Sefton Metropolitan Borough Council",
    "url": "https://www.sefton.gov.uk/",
    "tier": "unitary"
  },
  "Sevenoaks": {
    "slug": "sevenoaks",
    "name": "Sevenoaks District Council",
    "url": "http://www.sevenoaks.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Sheffield": {
    "slug": "sheffield",
    "name": "Sheffield City Council",
    "url": "https://www.sheffield.gov.uk/",
    "tier": "unitary"
  },
  "Shropshire": {
    "slug": "shropshire",
    "name": "Shropshire Council",
    "url": "https://next.shropshire.gov.uk/",
    "tier": "unitary"
  },
  "Slough": {
    "slug": "slough",
    "name": "Slough Borough Council",
    "url": "https://www.slough.gov.uk/",
    "tier": "unitary"
  },
  "Solihull": {
    "slug": "solihull",
    "name": "Solihull Metropolitan Borough Council",
    "url": "https://www.solihull.gov.uk/",
    "tier": "unitary"
  },
  "Somerset": {
    "slug": "somerset",
    "name": "Somerset Council",
    "url": "http://www.somerset.gov.uk/",
    "tier": "unitary"
  },
  "South Cambridgeshire": {
    "slug": "south-cambridgeshire",
    "name": "South Cambridgeshire District Council",
    "url": "http://www.scambs.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "cambridgeshire",
      "name": "Cambridgeshire County Council",
      "url": "https://www.cambridgeshire.gov.uk/"
    }
  },
  "South Derbyshire": {
    "slug": "south-derbyshire",
    "name": "South Derbyshire District Council",
    "url": "https://www.southderbyshire.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "derbyshire",
      "name": "Derbyshire County Council",
      "url": "https://www.derbyshire.gov.uk/"
    }
  },
  "South Gloucestershire": {
    "slug": "south-gloucestershire",
    "name": "South Gloucestershire Council",
    "url": "http://www.southglos.gov.uk/",
    "tier": "unitary"
  },
  "South Hams": {
    "slug": "south-hams",
    "name": "South Hams District Council",
    "url": "https://www.southhams.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "South Holland": {
    "slug": "south-holland",
    "name": "South Holland District Council",
    "url": "https://www.sholland.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "South Kesteven": {
    "slug": "south-kesteven",
    "name": "South Kesteven District Council",
    "url": "http://www.southkesteven.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "South Norfolk": {
    "slug": "south-norfolk",
    "name": "South Norfolk District Council",
    "url": "https://www.southnorfolkandbroadland.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "norfolk",
      "name": "Norfolk County Council",
      "url": "http://www.norfolk.gov.uk/"
    }
  },
  "South Oxfordshire": {
    "slug": "south-oxfordshire",
    "name": "South Oxfordshire District Council",
    "url": "http://www.southoxon.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "oxfordshire",
      "name": "Oxfordshire County Council",
      "url": "https://www.oxfordshire.gov.uk/"
    }
  },
  "South Ribble": {
    "slug": "south-ribble",
    "name": "South Ribble Borough Council",
    "url": "http://www.southribble.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "South Staffordshire": {
    "slug": "south-staffordshire",
    "name": "South Staffordshire Council",
    "url": "https://www.sstaffs.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "South Tyneside": {
    "slug": "south-tyneside",
    "name": "South Tyneside Council",
    "url": "http://www.southtyneside.gov.uk",
    "tier": "unitary"
  },
  "Southampton": {
    "slug": "southampton",
    "name": "Southampton City Council",
    "url": "http://www.southampton.gov.uk/",
    "tier": "unitary"
  },
  "Southend-on-Sea": {
    "slug": "southend-on-sea",
    "name": "Southend-on-Sea City Council",
    "url": "http://www.southend.gov.uk/",
    "tier": "unitary"
  },
  "Southwark": {
    "slug": "southwark",
    "name": "London Borough of Southwark",
    "url": "https://www.southwark.gov.uk/",
    "tier": "unitary"
  },
  "Spelthorne": {
    "slug": "spelthorne",
    "name": "Spelthorne Borough Council",
    "url": "http://www.spelthorne.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "St Albans": {
    "slug": "st-albans",
    "name": "St Albans City and District Council",
    "url": "https://www.stalbans.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "St. Helens": {
    "slug": "st-helens",
    "name": "St Helens Council",
    "url": "https://www.sthelens.gov.uk/",
    "tier": "unitary"
  },
  "Stafford": {
    "slug": "stafford",
    "name": "Stafford Borough Council",
    "url": "https://www.staffordbc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "Staffordshire Moorlands": {
    "slug": "staffordshire-moorlands",
    "name": "Staffordshire Moorlands District Council",
    "url": "https://www.staffsmoorlands.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "Stevenage": {
    "slug": "stevenage",
    "name": "Stevenage Borough Council",
    "url": "https://www.stevenage.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "Stockport": {
    "slug": "stockport",
    "name": "Stockport Metropolitan Borough Council",
    "url": "https://www.stockport.gov.uk/",
    "tier": "unitary"
  },
  "Stockton-on-Tees": {
    "slug": "stockton-on-tees",
    "name": "Stockton-on-Tees Borough Council",
    "url": "https://www.stockton.gov.uk/",
    "tier": "unitary"
  },
  "Stoke-on-Trent": {
    "slug": "stoke-on-trent",
    "name": "Stoke-on-Trent City Council",
    "url": "https://www.stoke.gov.uk/",
    "tier": "unitary"
  },
  "Stratford-on-Avon": {
    "slug": "stratford-on-avon",
    "name": "Stratford-on-Avon District Council",
    "url": "https://www.stratford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "warwickshire",
      "name": "Warwickshire County Council",
      "url": "https://www.warwickshire.gov.uk/"
    }
  },
  "Stroud": {
    "slug": "stroud",
    "name": "Stroud District Council",
    "url": "http://www.stroud.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "gloucestershire",
      "name": "Gloucestershire County Council",
      "url": "https://www.gloucestershire.gov.uk/"
    }
  },
  "Sunderland": {
    "slug": "sunderland",
    "name": "Sunderland City Council",
    "url": "https://www.sunderland.gov.uk/",
    "tier": "unitary"
  },
  "Surrey Heath": {
    "slug": "surrey-heath",
    "name": "Surrey Heath Borough Council",
    "url": "https://www.surreyheath.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Sutton": {
    "slug": "sutton",
    "name": "London Borough of Sutton",
    "url": "https://www.sutton.gov.uk/",
    "tier": "unitary"
  },
  "Swale": {
    "slug": "swale",
    "name": "Swale Borough Council",
    "url": "https://www.swale.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Swansea": {
    "slug": "swansea",
    "name": "City and County of Swansea Council",
    "url": "https://www.swansea.gov.uk/",
    "tier": "unitary"
  },
  "Swindon": {
    "slug": "swindon",
    "name": "Swindon Borough Council",
    "url": "https://www.swindon.gov.uk/",
    "tier": "unitary"
  },
  "Tameside": {
    "slug": "tameside",
    "name": "Tameside Metropolitan Borough Council",
    "url": "https://www.tameside.gov.uk/",
    "tier": "unitary"
  },
  "Tamworth": {
    "slug": "tamworth",
    "name": "Tamworth Borough Council",
    "url": "https://www.tamworth.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "staffordshire",
      "name": "Staffordshire County Council",
      "url": "https://www.staffordshire.gov.uk/"
    }
  },
  "Tandridge": {
    "slug": "tandridge",
    "name": "Tandridge District Council",
    "url": "https://www.tandridge.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Teignbridge": {
    "slug": "teignbridge",
    "name": "Teignbridge District Council",
    "url": "http://www.teignbridge.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "Telford and Wrekin": {
    "slug": "telford-and-wrekin",
    "name": "Telford & Wrekin Council",
    "url": "https://www.telford.gov.uk/",
    "tier": "unitary"
  },
  "Tendring": {
    "slug": "tendring",
    "name": "Tendring District Council",
    "url": "http://www.tendringdc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Test Valley": {
    "slug": "test-valley",
    "name": "Test Valley Borough Council",
    "url": "https://www.testvalley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Tewkesbury": {
    "slug": "tewkesbury",
    "name": "Tewkesbury Borough Council",
    "url": "https://tewkesbury.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "gloucestershire",
      "name": "Gloucestershire County Council",
      "url": "https://www.gloucestershire.gov.uk/"
    }
  },
  "Thanet": {
    "slug": "thanet",
    "name": "Thanet District Council",
    "url": "https://www.thanet.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Three Rivers": {
    "slug": "three-rivers",
    "name": "Three Rivers District Council",
    "url": "http://www.threerivers.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "Thurrock": {
    "slug": "thurrock",
    "name": "Thurrock Council",
    "url": "https://www.thurrock.gov.uk/",
    "tier": "unitary"
  },
  "Tonbridge and Malling": {
    "slug": "tonbridge-and-malling",
    "name": "Tonbridge and Malling Borough Council",
    "url": "https://www.tmbc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Torbay": {
    "slug": "torbay",
    "name": "Torbay Council",
    "url": "http://www.torbay.gov.uk/",
    "tier": "unitary"
  },
  "Torfaen": {
    "slug": "torfaen",
    "name": "Torfaen County Borough Council",
    "url": "https://www.torfaen.gov.uk/",
    "tier": "unitary"
  },
  "Torridge": {
    "slug": "torridge",
    "name": "Torridge District Council",
    "url": "https://www.torridge.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "Tower Hamlets": {
    "slug": "tower-hamlets",
    "name": "London Borough of Tower Hamlets",
    "url": "https://www.towerhamlets.gov.uk/",
    "tier": "unitary"
  },
  "Trafford": {
    "slug": "trafford",
    "name": "Trafford Metropolitan Borough Council",
    "url": "https://www.trafford.gov.uk/",
    "tier": "unitary"
  },
  "Tunbridge Wells": {
    "slug": "tunbridge-wells",
    "name": "Tunbridge Wells Borough Council",
    "url": "https://www.tunbridgewells.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "kent",
      "name": "Kent County Council",
      "url": "http://www.kent.gov.uk/"
    }
  },
  "Uttlesford": {
    "slug": "uttlesford",
    "name": "Uttlesford District Council",
    "url": "https://www.uttlesford.gov.uk/home",
    "tier": "district",
    "parent": {
      "slug": "essex",
      "name": "Essex County Council",
      "url": "https://www.essex.gov.uk/"
    }
  },
  "Vale of Glamorgan": {
    "slug": "vale-of-glamorgan",
    "name": "Vale of Glamorgan Council",
    "url": "https://valeofglamorgan.gov.uk/en/index.aspx",
    "tier": "unitary"
  },
  "Vale of White Horse": {
    "slug": "vale-of-white-horse",
    "name": "Vale of White Horse District Council",
    "url": "http://www.whitehorsedc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "oxfordshire",
      "name": "Oxfordshire County Council",
      "url": "https://www.oxfordshire.gov.uk/"
    }
  },
  "Wakefield": {
    "slug": "wakefield",
    "name": "Wakefield Metropolitan District Council",
    "url": "https://www.wakefield.gov.uk/",
    "tier": "unitary"
  },
  "Walsall": {
    "slug": "walsall",
    "name": "Walsall Metropolitan Borough Council",
    "url": "https://go.walsall.gov.uk/",
    "tier": "unitary"
  },
  "Waltham Forest": {
    "slug": "waltham-forest",
    "name": "London Borough of Waltham Forest",
    "url": "https://www.walthamforest.gov.uk/",
    "tier": "unitary"
  },
  "Wandsworth": {
    "slug": "wandsworth",
    "name": "London Borough of Wandsworth",
    "url": "https://www.wandsworth.gov.uk/",
    "tier": "unitary"
  },
  "Warrington": {
    "slug": "warrington",
    "name": "Warrington Borough Council",
    "url": "https://www.warrington.gov.uk/",
    "tier": "unitary"
  },
  "Warwick": {
    "slug": "warwick",
    "name": "Warwick District Council",
    "url": "https://www.warwickdc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "warwickshire",
      "name": "Warwickshire County Council",
      "url": "https://www.warwickshire.gov.uk/"
    }
  },
  "Watford": {
    "slug": "watford",
    "name": "Watford Borough Council",
    "url": "https://www.watford.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "Waverley": {
    "slug": "waverley",
    "name": "Waverley Borough Council",
    "url": "https://www.waverley.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Wealden": {
    "slug": "wealden",
    "name": "Wealden District Council",
    "url": "https://www.wealden.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "east-sussex",
      "name": "East Sussex County Council",
      "url": "https://www.eastsussex.gov.uk/"
    }
  },
  "Welwyn Hatfield": {
    "slug": "welwyn-hatfield",
    "name": "Welwyn Hatfield Council",
    "url": "https://www.welhat.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hertfordshire",
      "name": "Hertfordshire County Council",
      "url": "https://www.hertfordshire.gov.uk/"
    }
  },
  "West Berkshire": {
    "slug": "west-berkshire",
    "name": "West Berkshire Council",
    "url": "http://www.westberks.gov.uk/",
    "tier": "unitary"
  },
  "West Devon": {
    "slug": "west-devon",
    "name": "West Devon Borough Council",
    "url": "http://www.westdevon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "devon",
      "name": "Devon County Council",
      "url": "https://new.devon.gov.uk/"
    }
  },
  "West Lancashire": {
    "slug": "west-lancashire",
    "name": "West Lancashire Borough Council",
    "url": "http://www.westlancs.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "West Lindsey": {
    "slug": "west-lindsey",
    "name": "West Lindsey District Council",
    "url": "https://www.west-lindsey.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "lincolnshire",
      "name": "Lincolnshire County Council",
      "url": "https://www.lincolnshire.gov.uk/"
    }
  },
  "West Northamptonshire": {
    "slug": "west-northamptonshire",
    "name": "West Northamptonshire Council",
    "url": "https://www.westnorthants.gov.uk/",
    "tier": "unitary"
  },
  "West Oxfordshire": {
    "slug": "west-oxfordshire",
    "name": "West Oxfordshire District Council",
    "url": "https://www.westoxon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "oxfordshire",
      "name": "Oxfordshire County Council",
      "url": "https://www.oxfordshire.gov.uk/"
    }
  },
  "West Suffolk": {
    "slug": "west-suffolk",
    "name": "West Suffolk District Council",
    "url": "https://www.westsuffolk.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "suffolk",
      "name": "Suffolk County Council",
      "url": "http://www.suffolk.gov.uk/"
    }
  },
  "Westminster": {
    "slug": "westminster",
    "name": "City of Westminster",
    "url": "https://www.westminster.gov.uk/",
    "tier": "unitary"
  },
  "Westmorland and Furness": {
    "slug": "westmorland-and-furness",
    "name": "Westmorland and Furness Council",
    "url": "https://www.westmorlandandfurness.gov.uk/",
    "tier": "unitary"
  },
  "Wigan": {
    "slug": "wigan",
    "name": "Wigan Metropolitan Borough Council",
    "url": "https://www.wigan.gov.uk/",
    "tier": "unitary"
  },
  "Wiltshire": {
    "slug": "wiltshire",
    "name": "Wiltshire Council",
    "url": "https://www.wiltshire.gov.uk/",
    "tier": "unitary"
  },
  "Winchester": {
    "slug": "winchester",
    "name": "Winchester City Council",
    "url": "https://www.winchester.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "hampshire",
      "name": "Hampshire County Council",
      "url": "https://www.hants.gov.uk/"
    }
  },
  "Windsor and Maidenhead": {
    "slug": "windsor-and-maidenhead",
    "name": "Royal Borough of Windsor and Maidenhead",
    "url": "http://www.rbwm.gov.uk/",
    "tier": "unitary"
  },
  "Wirral": {
    "slug": "wirral",
    "name": "Wirral Council",
    "url": "http://www.wirral.gov.uk/",
    "tier": "unitary"
  },
  "Woking": {
    "slug": "woking",
    "name": "Woking Borough Council",
    "url": "https://www.woking.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "surrey",
      "name": "Surrey County Council",
      "url": "http://www.surreycc.gov.uk/"
    }
  },
  "Wokingham": {
    "slug": "wokingham",
    "name": "Wokingham Borough Council",
    "url": "https://www.wokingham.gov.uk/",
    "tier": "unitary"
  },
  "Wolverhampton": {
    "slug": "wolverhampton",
    "name": "City of Wolverhampton Council",
    "url": "http://www.wolverhampton.gov.uk",
    "tier": "unitary"
  },
  "Worcester": {
    "slug": "worcester",
    "name": "Worcester City Council",
    "url": "http://www.worcester.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "worcestershire",
      "name": "Worcestershire County Council",
      "url": "http://www.worcestershire.gov.uk"
    }
  },
  "Worthing": {
    "slug": "worthing",
    "name": "Worthing Borough Council",
    "url": "https://www.adur-worthing.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "west-sussex",
      "name": "West Sussex County Council",
      "url": "http://www.westsussex.gov.uk/"
    }
  },
  "Wrexham": {
    "slug": "wrexham",
    "name": "Wrexham County Borough Council",
    "url": "http://www.wrexham.gov.uk/",
    "tier": "unitary"
  },
  "Wychavon": {
    "slug": "wychavon",
    "name": "Wychavon District Council",
    "url": "http://www.wychavon.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "worcestershire",
      "name": "Worcestershire County Council",
      "url": "http://www.worcestershire.gov.uk"
    }
  },
  "Wyre": {
    "slug": "wyre",
    "name": "Wyre Council",
    "url": "http://www.wyre.gov.uk",
    "tier": "district",
    "parent": {
      "slug": "lancashire",
      "name": "Lancashire County Council",
      "url": "https://www.lancashire.gov.uk/"
    }
  },
  "Wyre Forest": {
    "slug": "wyre-forest",
    "name": "Wyre Forest District Council",
    "url": "https://www.wyreforestdc.gov.uk/",
    "tier": "district",
    "parent": {
      "slug": "worcestershire",
      "name": "Worcestershire County Council",
      "url": "http://www.worcestershire.gov.uk"
    }
  },
  "York": {
    "slug": "york",
    "name": "City of York Council",
    "url": "https://www.york.gov.uk/",
    "tier": "unitary"
  }
};
