// Police forces in England and Wales (ids from data.police.uk), with where to
// send a request for written confirmation from police records.
// PLACEHOLDER: contact details are filled in from each force website.

export const FORCES = {
  "avon-and-somerset": { name: "Avon and Somerset Constabulary", email: null, formUrl: null, sourceUrl: null },
  "bedfordshire": { name: "Bedfordshire Police", email: null, formUrl: null, sourceUrl: null },
  "cambridgeshire": { name: "Cambridgeshire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "cheshire": { name: "Cheshire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "city-of-london": { name: "City of London Police", email: null, formUrl: null, sourceUrl: null },
  "cleveland": { name: "Cleveland Police", email: null, formUrl: null, sourceUrl: null },
  "cumbria": { name: "Cumbria Constabulary", email: null, formUrl: null, sourceUrl: null },
  "derbyshire": { name: "Derbyshire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "devon-and-cornwall": { name: "Devon & Cornwall Police", email: null, formUrl: null, sourceUrl: null },
  "dorset": { name: "Dorset Police", email: null, formUrl: null, sourceUrl: null },
  "durham": { name: "Durham Constabulary", email: null, formUrl: null, sourceUrl: null },
  "dyfed-powys": { name: "Dyfed-Powys Police", email: null, formUrl: null, sourceUrl: null },
  "essex": { name: "Essex Police", email: null, formUrl: null, sourceUrl: null },
  "gloucestershire": { name: "Gloucestershire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "greater-manchester": { name: "Greater Manchester Police", email: null, formUrl: null, sourceUrl: null },
  "gwent": { name: "Gwent Police", email: null, formUrl: null, sourceUrl: null },
  "hampshire": { name: "Hampshire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "hertfordshire": { name: "Hertfordshire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "humberside": { name: "Humberside Police", email: null, formUrl: null, sourceUrl: null },
  "kent": { name: "Kent Police", email: null, formUrl: null, sourceUrl: null },
  "lancashire": { name: "Lancashire Constabulary", email: null, formUrl: null, sourceUrl: null },
  "leicestershire": { name: "Leicestershire Police", email: null, formUrl: null, sourceUrl: null },
  "lincolnshire": { name: "Lincolnshire Police", email: null, formUrl: null, sourceUrl: null },
  "merseyside": { name: "Merseyside Police", email: null, formUrl: null, sourceUrl: null },
  "metropolitan": { name: "Metropolitan Police Service", email: null, formUrl: null, sourceUrl: null },
  "norfolk": { name: "Norfolk Constabulary", email: null, formUrl: null, sourceUrl: null },
  "north-wales": { name: "North Wales Police", email: null, formUrl: null, sourceUrl: null },
  "north-yorkshire": { name: "North Yorkshire Police", email: null, formUrl: null, sourceUrl: null },
  "northamptonshire": { name: "Northamptonshire Police", email: null, formUrl: null, sourceUrl: null },
  "northumbria": { name: "Northumbria Police", email: null, formUrl: null, sourceUrl: null },
  "nottinghamshire": { name: "Nottinghamshire Police", email: null, formUrl: null, sourceUrl: null },
  "south-wales": { name: "South Wales Police", email: null, formUrl: null, sourceUrl: null },
  "south-yorkshire": { name: "South Yorkshire Police", email: null, formUrl: null, sourceUrl: null },
  "staffordshire": { name: "Staffordshire Police", email: null, formUrl: null, sourceUrl: null },
  "suffolk": { name: "Suffolk Constabulary", email: null, formUrl: null, sourceUrl: null },
  "surrey": { name: "Surrey Police", email: null, formUrl: null, sourceUrl: null },
  "sussex": { name: "Sussex Police", email: null, formUrl: null, sourceUrl: null },
  "thames-valley": { name: "Thames Valley Police", email: null, formUrl: null, sourceUrl: null },
  "warwickshire": { name: "Warwickshire Police", email: null, formUrl: null, sourceUrl: null },
  "west-mercia": { name: "West Mercia Police", email: null, formUrl: null, sourceUrl: null },
  "west-midlands": { name: "West Midlands Police", email: null, formUrl: null, sourceUrl: null },
  "west-yorkshire": { name: "West Yorkshire Police", email: null, formUrl: null, sourceUrl: null },
  "wiltshire": { name: "Wiltshire Police", email: null, formUrl: null, sourceUrl: null },
};
